### ISSUE TITLE
one clean sweep

### ISSUE THREAD

**Issue by tonyketcham** [samkravitz/discovery#8]
I got no issues...it's just so elegant..

**Comment by nbennett320** [comment]
truth 100

**Comment by samkravitz** [comment]
might need to reopen this... not sure if it's fixed...

**Comment by nbennett320** [comment]
o.O

**Comment by nbennett320** [comment]
> might need to reopen this... not sure if it's fixed...

its been fixed ever since version 0.0.06a, the big camelCase update
